
library(tidyverse)
library(cansim)
library(lubridate)

data<-get_cansim("25-10-0029-01")


data$REF_DATE<-parse_integer(data$REF_DATE)


names_to_rm<-c(3,6:11,13:21)
colnames(data)[names_to_rm]

data<- data %>%
  select(-colnames(data)[names_to_rm]) %>%
  pivot_wider(names_from="Supply and demand characteristics", values_from=VALUE) %>%
  filter(`Fuel type`=="Primary energy"|`Fuel type`=="Natural gas"|`Fuel type`=="Primary electricity, hydro and nuclear")

##Data Issues; 
#1) Ontario is missing Primary energy Availability data for 2017-2018, but can be calculated by backsumming from Net-Supply and adding in Natural Gas elec generation.
#2) Alberta is missing Primary energy Availability data for 2016-2018, but can be calculated by backsumming from Net-Supply. Alberta has Primary energy transformed into elec by utilities and industries for 2016-2018, but not for prior years. 
#3) British Columbia and Manitoba do not have Primary energy availability data, but a modified calculation can be done by adding Production, Imports, inter-regional transfers, Inter-product transfers and subtracting Exports

data_list<- data %>%
  group_split(`Fuel type`)
data.ng<- data_list[[1]]  #Natural Gas tibble
data.re<-data_list[[2]] #renewable energy tibble
data.pe<-data_list[[3]] #primary energy tibble

data.ng %>%
  mutate( elec = rowSums(data.ng[,11:12])) #calculate electricity generated by natural gas


data.pe<- data.pe %>% 
  mutate(
    `Transformed to electricity by utilities`= replace(`Transformed to electricity by utilities`,
                                                       GEO=="Ontario" & (REF_DATE==2016|REF_DATE==2015|REF_DATE==2017|REF_DATE==2018),
                                                       data.ng$`Transformed to electricity by utilities`[data.ng$GEO=="Ontario" & (data.ng$REF_DATE==2016|data.ng$REF_DATE==2015|data.ng$REF_DATE==2017|data.ng$REF_DATE==2018)]
    ),
    `Transformed to electricity by industry`= replace(`Transformed to electricity by industry`,
                                                      GEO=="Ontario" & (REF_DATE==2016|REF_DATE==2015|REF_DATE==2017|REF_DATE==2018),
                                                      data.ng$`Transformed to electricity by industry`[data.ng$GEO=="Ontario" & (data.ng$REF_DATE==2016|data.ng$REF_DATE==2015|data.ng$REF_DATE==2017|data.ng$REF_DATE==2018)]
    )
  )


data.pe<-data.pe %>%
  mutate(
    Avail_est = rowSums(data.pe[,10:16], na.rm=TRUE),
    Availability=replace(Availability,
                         (GEO=="Ontario"|GEO=="Alberta") & (REF_DATE==2016|REF_DATE==2017|REF_DATE==2018) & is.na(Availability),
                         Avail_est[(GEO=="Ontario"|GEO=="Alberta") & (REF_DATE==2016|REF_DATE==2017|REF_DATE==2018)  & is.na(Availability)]
    )) 


#check to make sure Avail_est matches Availability for 2015 and 2016 to confirm method for Ontario. To confirm the method for Alberta, need to add the elec generated by coal data for 2014-2015, but I checked it manually using Excel and it works out
data.pe%>%
  filter( (GEO=="Ontario") & (REF_DATE==2015|REF_DATE==2016)) %>%
  select(REF_DATE,GEO,Availability, Avail_est)



names<-colnames(data.pe)[c(4:9,48)]

data.pe<- data.pe %>%
  mutate(
    Exports = -1*Exports,
    `Stock variation`= -1*`Stock variation`)

data.pe<-data.pe %>%
  mutate(
    Avail_est2= select(.,names) %>% rowSums(na.rm=TRUE),
    Availability=replace(Availability,
                         (GEO=="British Columbia"|GEO=="Manitoba"),
                         Avail_est2[(GEO=="British Columbia"|GEO=="Manitoba")]
    )) 


data.pe %>%
  ggplot(aes(REF_DATE,Availability))+
  geom_line()+
  facet_wrap(~GEO)



dta<-data.pe %>%
  select(REF_DATE,GEO,Availability) %>%
  rename(
    Primary = Availability
  )

data.re1<-data.re %>%
  select(REF_DATE,GEO,Availability)

energy_dta<- dta %>%
  left_join(data.re1) %>%
  rename(
    NonFossil = Availability,
    Year = REF_DATE,
    Energy = Primary
  ) %>%
  mutate(
    Fossil = Energy - NonFossil,
    ShareFossil = Fossil/Energy
  ) 


energy_dta %>%
  filter(GEO=="Alberta"|GEO=="British Columbia"|GEO=="Canada"|GEO=="Atlantic provinces"|GEO=="Manitoba"|GEO=="Ontario"|GEO=="Quebec") %>%
  ggplot(aes(Year,ShareFossil))+
  geom_line()+
  facet_wrap(~GEO)

#Something weird with the Manitoba data; 1995-2003 MB had massive annual "Inter-regional transfers" and then "Exports". In 2004-2018 these amounts are much, much lower. Possibly a change in how oil shipped through MB in TransCanada pipeline was accounted?

data<-get_cansim("36-10-0222-01") %>%
  normalize_cansim_values

data$REF_DATE<-parse_integer(data$REF_DATE)

names_to_rm<-c(3,6:9,11:20)
colnames(data)[names_to_rm]

data %>%
  select(-colnames(data)[names_to_rm]) %>%
  filter(Prices=="Chained (2012) dollars",Estimates=="Gross domestic product at market prices") 


atl_provs<-unique(data$GEO)[2:5]


atl_gdp<- data %>%
  filter(GEO %in% atl_provs) %>%
  group_by(REF_DATE) %>%
  summarise( "Atlantic provinces" = sum(VALUE)) %>%
  pivot_longer("Atlantic provinces",names_to="GEO",values_to="GDP") %>%
  rename(Year=REF_DATE)

roc_gdp<-data %>%
  filter(GEO=="Alberta"|GEO=="British Columbia"|GEO=="Canada"|GEO=="Manitoba"|GEO=="Ontario"|GEO=="Quebec") %>%
  rename(GDP = VALUE, Year=REF_DATE) %>%
  select(Year, GEO, GDP) 

gdp<-bind_rows(roc_gdp,atl_gdp)

#Get Greenhouse Gas Emissions Data from Environment Canada
ghg_data<-read_csv("http://donnees.ec.gc.ca/data/substances/monitor/canada-s-official-greenhouse-gas-inventory/GHG_IPCC_Can_Prov_Terr.csv")

atl_ghgs<- ghg_data %>%
  filter(Region %in% atl_provs,Category=="TOTAL") %>%
  group_by(Year) %>%
  summarise( "Atlantic provinces" = sum(CO2eq)*1000) %>%
  pivot_longer("Atlantic provinces",names_to="GEO",values_to="CO2")

ghg_data2<-ghg_data %>%
  mutate( CO2eq = CO2eq*1000) %>%
  filter(Category=="TOTAL",(Region=="Alberta"|Region=="British Columbia"|Region=="Canada"|Region=="Manitoba"|Region=="Ontario"|Region=="Quebec")) %>%
  select(Year,Region,CO2eq) %>%
  rename(GEO=Region,CO2=CO2eq) %>%
  bind_rows(.,atl_ghgs)


#next step is combining the tibbles by (Year,GEO)



